-- Migration 009: Stage 5 Evolution Events
--
-- Records deterministic historical facts generated by correlating
-- Git history with static code analysis.

CREATE TABLE public.repository_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    repo_id UUID NOT NULL REFERENCES public.repositories(id) ON DELETE CASCADE,
    commit_id UUID REFERENCES public.commits(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    event_key TEXT NOT NULL,
    description TEXT,
    event_date TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- Idempotency / Duplicate Prevention constraint
CREATE UNIQUE INDEX idx_repository_events_unique 
    ON public.repository_events(repo_id, commit_id, event_type, event_key);

-- Query performance indexes
CREATE INDEX idx_repository_events_repo_date ON public.repository_events(repo_id, event_date DESC);
CREATE INDEX idx_repository_events_commit_id ON public.repository_events(commit_id);

ALTER TABLE public.repository_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can access their repository events" ON public.repository_events
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.repositories 
            WHERE id = repository_events.repo_id 
            AND user_id = auth.uid()
        )
    );
